### PR TITLE
Update git-mirror-task.ts

### PR DESCRIPTION
**Pull request by dvanicek-idc**
Removing also merge-requests from mirroring as discussed here: https://github.com/swellaby/vsts-mirror-git-repository/issues/125

## Changes
Summary of changes included in this PR:
- [ ]
- [ ]
- [ ]

## Issues Completed
- Closes #
- Closes #

CC - @traviskosarek @calebcartwright

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thanks for the PR! It looks like CI checks are failing due to the proposed changes not being covered by any new tests. You should be able to see this locally via `npm test`, and/or `npm run cov-open` if you prefer the more detailed html report.

I think this can be addressed fairly easily by updating the test data to incorporate a ref for a merge-request, probably somewhere in this vicinity:

https://github.com/swellaby/vsts-mirror-git-repository/blob/8c23abd4d906ac5b9f15cb43c6e731150fb155b4/src/git-mirror/git-mirror-task.spec.ts#L271-L291

Most likely by creating a new MR ref similar to:

https://github.com/swellaby/vsts-mirror-git-repository/blob/8c23abd4d906ac5b9f15cb43c6e731150fb155b4/src/git-mirror/git-mirror-task.spec.ts#L285

and then adding that new ref line to the packed refs data here:

https://github.com/swellaby/vsts-mirror-git-repository/blob/8c23abd4d906ac5b9f15cb43c6e731150fb155b4/src/git-mirror/git-mirror-task.spec.ts#L290-L291

**Comment by dvanicek-idc** [comment]
I tried to add this according your notes. Seems still failing on code coverage

**Comment by dvanicek-idc** [comment]
I kept the changes for unit tests, but deleted the filtering part in script. I guess the tests should fail, but they are passing

**Comment by dvanicek-idc** [comment]
Anyone can help? :-)

**Comment by calebcartwright** [comment]
Acknowledge seeing this, but haven't had time to take a closer look.

**Comment by calebcartwright** [comment]
Confirming I can reproduce. I know what the problem is in the test structure and how to fix, so if you can add back in the filter clause for the merge-requests refs then I'll go ahead and merge and fix the assertion issue afterwards

**Comment by dvanicek-idc** [comment]
Thanks for checking this! I added back the filtering part.

**Review by calebcartwright — APPROVED** [review]

**Comment by calebcartwright** [comment]
Thanks! I'm going to fix the assertions and will then try to see if we can get a release pushed through

**Pull request merged**
